import { DimenúvelInfo, SoundPreset, AudioLayer } from '../types';

export const DIMENUVEIS_INFO: DimenúvelInfo[] = [
  {
    id: 1,
    name: 'Silêncio',
    subtitle: '1ª Dimenúvel — O Ponto de Partida',
    symbol: '◯',
    color: '#e2e8f0', // Silver-white
    accentColor: '#94a3b8',
    description: 'Som mínimo e essencial. O espaço antes da manifestação e a quietude fundamental.',
    contemplativeFocus: 'Repouso da mente, quietude interior e percepção do vazio fecundo.',
    suggestedBaseFreq: 64,
    suggestedBeatFreq: 2.0,
  },
  {
    id: 2,
    name: 'Visão',
    subtitle: '2ª Dimenúvel — A Percepção Espacial',
    symbol: '◎',
    color: '#818cf8', // Indigo / Soft Violet
    accentColor: '#6366f1',
    description: 'Ambiente espaçoso de transformação lenta. Abertura do campo perceptivo e amplitude.',
    contemplativeFocus: 'Observação sem apego, expansão do horizonte e contemplação.',
    suggestedBaseFreq: 144,
    suggestedBeatFreq: 6.0,
  },
  {
    id: 3,
    name: 'Mente',
    subtitle: '3ª Dimenúvel — O Padrão Lúcido',
    symbol: '◇',
    color: '#38bdf8', // Sky Blue / Cyan
    accentColor: '#0284c7',
    description: 'Padrões organizados e lúcidos. Harmonia matemática, clareza e discernimento sereno.',
    contemplativeFocus: 'Clareza de pensamento, presença consciente e ordenação interior.',
    suggestedBaseFreq: 216,
    suggestedBeatFreq: 10.0,
  },
  {
    id: 4,
    name: 'Coração',
    subtitle: '4ª Dimenúvel — A Ressonância Acolhedora',
    symbol: '♡',
    color: '#34d399', // Emerald / Warm Sage
    accentColor: '#10b981',
    description: 'Modulação suave, calor e ressonância. A dimensão do acolhimento e da comunhão.',
    contemplativeFocus: 'Empatia, aceitação, serenidade cordial e dissolução de resistências.',
    suggestedBaseFreq: 136.1,
    suggestedBeatFreq: 5.5,
  },
  {
    id: 5,
    name: 'Vontade',
    subtitle: '5ª Dimenúvel — A Direção e o Foco',
    symbol: '△',
    color: '#fbbf24', // Amber Gold
    accentColor: '#f59e0b',
    description: 'Estrutura rítmica definida. O impulso da intenção consciente e da determinação serena.',
    contemplativeFocus: 'Foco sustentado, firmeza de propósito e presença ativa no agora.',
    suggestedBaseFreq: 256,
    suggestedBeatFreq: 14.0,
  },
  {
    id: 6,
    name: 'Energia',
    subtitle: '6ª Dimenúvel — O Movimento Vibrante',
    symbol: '✹',
    color: '#f97316', // Vibrant Orange / Citrine
    accentColor: '#ea580c',
    description: 'Movimento e atividade rítmica expansiva. O dinamismo da criação e a força viva.',
    contemplativeFocus: 'Vitalidade desperta, circulação da atenção e dinamismo consciente.',
    suggestedBaseFreq: 320,
    suggestedBeatFreq: 18.0,
  },
  {
    id: 7,
    name: 'Matéria',
    subtitle: '7ª Dimenúvel — O Aterramento Profundo',
    symbol: '□',
    color: '#a87954', // Earth Terracotta / Bronze
    accentColor: '#845738',
    description: 'Frequências graves, sustentadas e telúricas. O ancoramento no corpo e na realidade física.',
    contemplativeFocus: 'Aterramento corpóreo, peso agradável, estabilidade e presença sólida.',
    suggestedBaseFreq: 72,
    suggestedBeatFreq: 3.5,
  },
];

export const CANONICAL_PRESETS: SoundPreset[] = [
  {
    id: 'dimenuvel-1-silencio',
    name: '1. Silêncio',
    dimenuvelId: 1,
    description: 'Som mínimo e essencial. Um tom sub-harmônico suave com pulso lento de 2 Hz.',
    category: 'canonical',
    masterVolume: 0.7,
    isDefault: true,
    layers: [
      {
        id: 'layer-sil-1',
        name: 'Vazio Primordial (Binaural 2 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 64,
        rightFreq: 66,
        waveform: 'sine',
        volume: 0.55,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.1, // 6 BPM slow breathing LFO
          bpm: 6,
          depth: 0.25,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#e2e8f0',
        dimenuvelId: 1,
      },
      {
        id: 'layer-sil-2',
        name: 'Sopro Sutil (Harmônico 128 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 128,
        rightFreq: 128,
        waveform: 'sine',
        volume: 0.18,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.05,
          bpm: 3,
          depth: 0.2,
          waveform: 'triangle',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#94a3b8',
        dimenuvelId: 1,
      },
    ],
  },
  {
    id: 'dimenuvel-2-visao',
    name: '2. Visão',
    dimenuvelId: 2,
    description: 'Ambiente espaçoso com pulso de 6 Hz e harmônico brilhante de 432 Hz.',
    category: 'canonical',
    masterVolume: 0.7,
    isDefault: true,
    layers: [
      {
        id: 'layer-vis-1',
        name: 'Campo Espacial (Binaural 6 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 144,
        rightFreq: 150,
        waveform: 'sine',
        volume: 0.5,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.2,
          bpm: 12,
          depth: 0.3,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: true,
        },
        color: '#818cf8',
        dimenuvelId: 2,
      },
      {
        id: 'layer-vis-2',
        name: 'Horizonte Aberto (432 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 432,
        rightFreq: 432,
        waveform: 'triangle',
        volume: 0.25,
        pan: 0.2,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.15,
          bpm: 9,
          depth: 0.4,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#a5b4fc',
        dimenuvelId: 2,
      },
      {
        id: 'layer-vis-3',
        name: 'Sub-harmônico de Sustentação (72 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 72,
        rightFreq: 72,
        waveform: 'sine',
        volume: 0.3,
        pan: -0.2,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.15,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#6366f1',
        dimenuvelId: 2,
      },
    ],
  },
  {
    id: 'dimenuvel-3-mente',
    name: '3. Mente',
    dimenuvelId: 3,
    description: 'Padrão lúcido e ordenado com pulso Alpha de 10 Hz e harmônico tríade de 216 Hz.',
    category: 'canonical',
    masterVolume: 0.7,
    isDefault: true,
    layers: [
      {
        id: 'layer-men-1',
        name: 'Clareza Alpha (Binaural 10 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 216,
        rightFreq: 226,
        waveform: 'sine',
        volume: 0.5,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.25,
          bpm: 15,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#38bdf8',
        dimenuvelId: 3,
      },
      {
        id: 'layer-men-2',
        name: 'Estrutura Harmônica (324 Hz — 3/2 Quinta)',
        type: 'monaural',
        enabled: true,
        leftFreq: 324,
        rightFreq: 324,
        waveform: 'triangle',
        volume: 0.22,
        pan: -0.3,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.5,
          bpm: 30,
          depth: 0.3,
          waveform: 'triangle',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#7dd3fc',
        dimenuvelId: 3,
      },
      {
        id: 'layer-men-3',
        name: 'Base Theta de Observação (108 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 108,
        rightFreq: 108,
        waveform: 'sine',
        volume: 0.35,
        pan: 0.3,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#0284c7',
        dimenuvelId: 3,
      },
    ],
  },
  {
    id: 'dimenuvel-4-coracao',
    name: '4. Coração',
    dimenuvelId: 4,
    description: 'Modulação calorosa baseada no tom ressonante de 136.1 Hz e pulso suave de 5.5 Hz.',
    category: 'canonical',
    masterVolume: 0.7,
    isDefault: true,
    layers: [
      {
        id: 'layer-cor-1',
        name: 'Tom Acolhedor (Binaural 5.5 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 136.1,
        rightFreq: 141.6,
        waveform: 'sine',
        volume: 0.55,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.12, // Slow 7.2 bpm wave
          bpm: 7,
          depth: 0.35,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#34d399',
        dimenuvelId: 4,
      },
      {
        id: 'layer-cor-2',
        name: 'Oitava Aconchegante (272.2 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 272.2,
        rightFreq: 272.2,
        waveform: 'triangle',
        volume: 0.25,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.08,
          bpm: 5,
          depth: 0.3,
          waveform: 'triangle',
          mode: 'continuous',
          autoPan: true,
        },
        color: '#6ee7b7',
        dimenuvelId: 4,
      },
      {
        id: 'layer-cor-3',
        name: 'Quinta Dourada (204.15 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 204.15,
        rightFreq: 204.15,
        waveform: 'sine',
        volume: 0.2,
        pan: -0.15,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#10b981',
        dimenuvelId: 4,
      },
    ],
  },
  {
    id: 'dimenuvel-5-vontade',
    name: '5. Vontade',
    dimenuvelId: 5,
    description: 'Estrutura rítmica com pulso de 14 Hz e base sólida em 256 Hz.',
    category: 'canonical',
    masterVolume: 0.7,
    isDefault: true,
    layers: [
      {
        id: 'layer-von-1',
        name: 'Intenção Firme (Binaural 14 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 256,
        rightFreq: 270,
        waveform: 'sine',
        volume: 0.5,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.3,
          bpm: 18,
          depth: 0.25,
          waveform: 'triangle',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#fbbf24',
        dimenuvelId: 5,
      },
      {
        id: 'layer-von-2',
        name: 'Pulso Rítmico Marcado (384 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 384,
        rightFreq: 384,
        waveform: 'sawtooth',
        volume: 0.14,
        pan: 0.25,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 2.0, // 120 bpm rhythmic pulse
          bpm: 120,
          depth: 0.6,
          waveform: 'square',
          mode: 'pulse',
          autoPan: false,
        },
        color: '#fde68a',
        dimenuvelId: 5,
      },
      {
        id: 'layer-von-3',
        name: 'Fundação de Vontade (128 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 128,
        rightFreq: 128,
        waveform: 'sine',
        volume: 0.35,
        pan: -0.25,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#f59e0b',
        dimenuvelId: 5,
      },
    ],
  },
  {
    id: 'dimenuvel-6-energia',
    name: '6. Energia',
    dimenuvelId: 6,
    description: 'Movimento vibrante com modulação dinâmica de 18 Hz e pulsação estéreo.',
    category: 'canonical',
    masterVolume: 0.7,
    isDefault: true,
    layers: [
      {
        id: 'layer-ene-1',
        name: 'Vibração Dinâmica (Binaural 18 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 320,
        rightFreq: 338,
        waveform: 'sine',
        volume: 0.48,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 1.5,
          bpm: 90,
          depth: 0.4,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: true,
        },
        color: '#f97316',
        dimenuvelId: 6,
      },
      {
        id: 'layer-ene-2',
        name: 'Pulso Cintilante (480 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 480,
        rightFreq: 480,
        waveform: 'triangle',
        volume: 0.2,
        pan: 0.35,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 3.0,
          bpm: 180,
          depth: 0.5,
          waveform: 'triangle',
          mode: 'pulse',
          autoPan: false,
        },
        color: '#fdba74',
        dimenuvelId: 6,
      },
      {
        id: 'layer-ene-3',
        name: 'Sub-pulso de Movimento (160 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 160,
        rightFreq: 160,
        waveform: 'sawtooth',
        volume: 0.15,
        pan: -0.35,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.5,
          bpm: 30,
          depth: 0.45,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#ea580c',
        dimenuvelId: 6,
      },
    ],
  },
  {
    id: 'dimenuvel-7-materia',
    name: '7. Matéria',
    dimenuvelId: 7,
    description: 'Frequências graves, sustentadas e telúricas com pulso delta de 3.5 Hz.',
    category: 'canonical',
    masterVolume: 0.75,
    isDefault: true,
    layers: [
      {
        id: 'layer-mat-1',
        name: 'Ancoragem Telúrica (Binaural 3.5 Hz)',
        type: 'binaural',
        enabled: true,
        leftFreq: 72,
        rightFreq: 75.5,
        waveform: 'sine',
        volume: 0.6,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.08,
          bpm: 5,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#a87954',
        dimenuvelId: 7,
      },
      {
        id: 'layer-mat-2',
        name: 'Ressonância Física (108 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 108,
        rightFreq: 108,
        waveform: 'triangle',
        volume: 0.35,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.1,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#d4a373',
        dimenuvelId: 7,
      },
      {
        id: 'layer-mat-3',
        name: 'Sub-Grave Profundo (54 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 54,
        rightFreq: 54,
        waveform: 'sine',
        volume: 0.4,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.05,
          bpm: 3,
          depth: 0.1,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#845738',
        dimenuvelId: 7,
      },
    ],
  },
];

export const CONTEMPLATIVE_PRESETS: SoundPreset[] = [
  {
    id: 'preset-espiral-aurea',
    name: 'A Espiral Áurea (φ 1.618)',
    description: 'Camadas proporcionais à proporção áurea com 432 Hz como semente central.',
    category: 'contemplative',
    masterVolume: 0.7,
    layers: [
      {
        id: 'layer-esp-1',
        name: 'Base Áurea (267 Hz → 275 Hz | 8 Hz Alpha)',
        type: 'binaural',
        enabled: true,
        leftFreq: 267,
        rightFreq: 275,
        waveform: 'sine',
        volume: 0.5,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.15,
          bpm: 9,
          depth: 0.25,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: true,
        },
        color: '#e5c158',
      },
      {
        id: 'layer-esp-2',
        name: 'Harmônico φ (432 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 432,
        rightFreq: 432,
        waveform: 'sine',
        volume: 0.3,
        pan: -0.3,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.24,
          bpm: 14,
          depth: 0.35,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#c5a059',
      },
      {
        id: 'layer-esp-3',
        name: 'Harmônico Superior φ² (699 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 699,
        rightFreq: 699,
        waveform: 'triangle',
        volume: 0.16,
        pan: 0.3,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.39,
          bpm: 23,
          depth: 0.4,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#d4af37',
      },
    ],
  },
  {
    id: 'preset-o-padrao',
    name: 'O Padrão (Tríade Harmônica 528 Hz)',
    description: 'Exploração contemplativa da frequência de 528 Hz em tríade equilibrada.',
    category: 'contemplative',
    masterVolume: 0.7,
    layers: [
      {
        id: 'layer-pad-1',
        name: 'Centro do Padrão (528 Hz Binaural 7.83 Hz Schumann)',
        type: 'binaural',
        enabled: true,
        leftFreq: 528,
        rightFreq: 535.83,
        waveform: 'sine',
        volume: 0.45,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.2,
          bpm: 12,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#34d399',
      },
      {
        id: 'layer-pad-2',
        name: 'Sub-oitava (264 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 264,
        rightFreq: 264,
        waveform: 'triangle',
        volume: 0.35,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.2,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#10b981',
      },
      {
        id: 'layer-pad-3',
        name: 'Ancoragem Grave (132 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 132,
        rightFreq: 132,
        waveform: 'sine',
        volume: 0.4,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.05,
          bpm: 3,
          depth: 0.15,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#059669',
      },
    ],
  },
  {
    id: 'preset-o-espelho',
    name: 'O Espelho (Fases Cruzadas)',
    description: 'Dois pares binaurais opostos criando um campo sonoro tridimensional imersivo.',
    category: 'contemplative',
    masterVolume: 0.7,
    layers: [
      {
        id: 'layer-esp-a',
        name: 'Espelho Esquerdo (180 Hz → 186 Hz | 6 Hz Theta)',
        type: 'binaural',
        enabled: true,
        leftFreq: 180,
        rightFreq: 186,
        waveform: 'sine',
        volume: 0.45,
        pan: -0.4,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.3,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#a78bfa',
      },
      {
        id: 'layer-esp-b',
        name: 'Espelho Direito (186 Hz → 180 Hz | 6 Hz Invertido)',
        type: 'binaural',
        enabled: true,
        leftFreq: 186,
        rightFreq: 180,
        waveform: 'sine',
        volume: 0.45,
        pan: 0.4,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.3,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#c4b5fd',
      },
      {
        id: 'layer-esp-c',
        name: 'Eixo Central de Sustentação (90 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 90,
        rightFreq: 90,
        waveform: 'triangle',
        volume: 0.3,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: false,
          rateHz: 0.05,
          bpm: 3,
          depth: 0.15,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#7c3aed',
      },
    ],
  },
  {
    id: 'preset-respiracao-abidar',
    name: 'Abidar — Respiração Contemplativa',
    description: 'Cadência lenta sincronizada em 6 respirações por minuto (0.1 Hz) para ancoramento na presença.',
    category: 'contemplative',
    masterVolume: 0.7,
    layers: [
      {
        id: 'layer-res-1',
        name: 'Onda de Presença (200 Hz → 204 Hz | 4 Hz Theta)',
        type: 'binaural',
        enabled: true,
        leftFreq: 200,
        rightFreq: 204,
        waveform: 'sine',
        volume: 0.5,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.1, // Exactly 6 breaths per minute cycle
          bpm: 6,
          depth: 0.5,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: false,
        },
        color: '#38bdf8',
      },
      {
        id: 'layer-res-2',
        name: 'Pulso de Respiração Suave (100 Hz)',
        type: 'monaural',
        enabled: true,
        leftFreq: 100,
        rightFreq: 100,
        waveform: 'triangle',
        volume: 0.35,
        pan: 0,
        mute: false,
        solo: false,
        modulation: {
          enabled: true,
          rateHz: 0.1,
          bpm: 6,
          depth: 0.4,
          waveform: 'sine',
          mode: 'continuous',
          autoPan: true,
        },
        color: '#0284c7',
      },
    ],
  },
];

export const ALL_DEFAULT_PRESETS: SoundPreset[] = [
  ...CANONICAL_PRESETS,
  ...CONTEMPLATIVE_PRESETS,
];

export function createBlankLayer(name = 'Nova Camada', count = 1): AudioLayer {
  const baseFreq = 200 + (count * 40);
  return {
    id: `layer-custom-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
    name,
    type: 'binaural',
    enabled: true,
    leftFreq: baseFreq,
    rightFreq: baseFreq + 8,
    waveform: 'sine',
    volume: 0.45,
    pan: 0,
    mute: false,
    solo: false,
    modulation: {
      enabled: false,
      rateHz: 0.2,
      bpm: 12,
      depth: 0.3,
      waveform: 'sine',
      mode: 'continuous',
      autoPan: false,
    },
    color: '#d4af37',
  };
}
